### ISSUE TITLE
how to stop conversation?

### ISSUE THREAD

**Issue by kamil-malinski** [microsoft/conversational-speaker#12]
Hi!

How to stop the conversation? Is there an equivalent to the wake word to stop the conversation?

Kamil

**Comment by adrianwyatt** [comment]
If you say just "Goodbye", it will respond and then stop listening.

**Comment by kamil-malinski** [comment]
thanks! is it possible to change the goodbye-phrase?

**Comment by adrianwyatt** [comment]
Yup! I haven't broken it out into a configuration setting, but the line of code is here: https://github.com/microsoft/conversational-speaker/blob/main/src/ConversationalSpeaker/HostedServices/HostedService.cs#L128

**Comment by adrianwyatt** [comment]
Or just search for "goodbye" in the other branches if you're coming from hackster. :)

**Comment by kamil-malinski** [comment]
great, thanks a lot!
