### ISSUE TITLE
Speech Recognizer Session Canceled Runtime Error

### ISSUE THREAD

**Issue by Optionalpoop** [microsoft/conversational-speaker#16]
Whenever I run dotnet run and say the keyword, it just gives me the following set of text on loop until I stop the program.

[12:54:32] info: Listening...
[12:54:33] warn: Speech recognizer session canceled.
[12:54:33] warn: Error: RuntimeError

**Comment by Optionalpoop** [comment]
Also, is it possible to not have to pay for the openai software, my trial ran out, but I obviously dont want to pay to use the software, even when chatgpt is free normally?

**Comment by adrianwyatt** [comment]
The speech recognizer cancellation can occur if the Azure Speech SDK is having trouble finding your microphone. You can enable additional log messages by updating the `Logging` section in `configuration.json`. Change `"Default": "Information"` to `"Default": "Debug"`, then rebuild and rerun to get additional details on the failure. Please re-open/re-create an issue if you are still having issues.

**Comment by adrianwyatt** [comment]
I'm afraid I don't know of any other  free options beyond OpenAI's trial. Though the pricing for gpt-3.5-turbo is 10x less expensive than it used to be. It's currently priced at USD$0.002 / 1,000 tokens with a token being about 3/4s of a word on average.
