### ISSUE TITLE
Speech Recognizer Session Canceled Issue

### ISSUE THREAD

**Issue by Mystic19** [microsoft/conversational-speaker#8]
I keep running into this issue. (see screenshot)
![IMG_20230322_152636_733](https://user-images.githubusercontent.com/22962714/227368357-73edaff6-6954-42d8-9f1f-549a4400f3d8.jpg)

**Comment by adrianwyatt** [comment]
Thank you for the issue and my apologies for not getting back to you sooner. I have added logging to the case where the speech recognizer fails. If you are still seeing the issue, please update your code to the latest in the `main` branch and create an issue with the error messages. 

For lots of good logging in this scenario, in `appsettings.json`, set `Logging:LogLevel:Default` to `Debug`. Thanks again!

**Comment by Mystic19** [comment]
No worries, the issue has been resolved. However, I noticed that with the free Azure trial subscription, once you're connected to the cloud, it just freeze.
